### PR TITLE
Add support to elixir releases

### PR DESCRIPTION
**Pull request by rockneurotiko**
Handles the issue #8 and adds support for Elixir Releases!

### CODE REVIEW

**Comment by juantascon** [comment]
hey, is this getting merged soon? I'm in the middle of migrating to elixir 1.9 releases and this would make my life so much easier

**Comment by rockneurotiko** [comment]
@juantascon let me do one last test to see if it's working correctly and I'll merge and release it

**Comment by rockneurotiko** [comment]
@juantascon Merged and released the `0.4.0` version with it

**Comment by juantascon** [comment]
thank you!

**Pull request merged**
